server:
  port: 8189
  servlet:
    context-path: /core
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:db
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

integrations:
  cart-service:
    url: http://localhost:8199/cart/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000